@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class contracts {
   startdate: date
   cancellation_date  /* only set when cancelled */: date
   cancellation_period  /* in months */: int
   individual_price  /* in cents */: int
   price_guarantee_period  /* in months */: int
   meter_id: varchar(50)
   file_location  /* information where contract is archived */: varchar(50)
   type_id: int
   household_id: int
   id: int
}
class customer {
   household_id  /* fetched from rathaus */: int
   first_name  /* billing address */: varchar(50)
   last_name  /* billing address */: varchar(50)
   street  /* billing address */: varchar(50)
   street_nr  /* billing address */: varchar(5)
   plz  /* billing adress */: int
   city  /* billing address */: varchar(50)
   has_completed_signup: tinyint(1)
   id: int
}
class invoicings {
   amount_due  /* in cents */: int
   amount_paid  /* in cents */: int
   date_due: date
   amount_consumed  /* of energy in contract unit */: int
   contract_id: int
   id: int
}
class meter_readings {
   meter_id: varchar(50)
   reading: int
   date: date
   contract: int
   id: int
}
class role_assignment {
   user_id: int
   role_id: int
}
class roles {
   name: varchar(50)
   id: int
}
class tariffs {
   name: int
   description: int
   price  /* in cents */: int
   unit: enum('m3', 'kwh')
   category: enum('water', 'gas', 'electricity', 'heat_pump')
   id: int
}
class translations {
   content: varchar(200)
   id: int
   language: enum('de', 'en')
}
class node0 as "userdata  /* all data except customer_id fetched from rathaus */" {
   first_name: varchar(50)
   last_name: varchar(50)
   birthdate: date
   mail: varchar(50)
   country_code: int
   phone: int
   customer_id: int
   id: int
}

contracts        -[#595959,plain]-^  customer        : "household_id:id"
contracts        -[#595959,plain]-^  tariffs         : "type_id:id"
invoicings       -[#595959,plain]-^  contracts       : "contract_id:id"
meter_readings   -[#595959,plain]-^  contracts       : "contract:id"
role_assignment  -[#595959,plain]-^  roles           : "role_id:id"
role_assignment  -[#595959,plain]-^  node0           : "user_id:id"
tariffs          -[#595959,plain]-^  translations    : "description:id"
tariffs          -[#595959,plain]-^  translations    : "name:id"
node0            -[#595959,plain]-^  customer        : "customer_id:id"
@enduml
